{% set name = "flux-sched" %}
{% set version = "0.33.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flux-framework/flux-sched/releases/download/v{{ version }}/flux-sched-{{ version }}.tar.gz
  sha256: d0a1e504226d69fa8a247e9090d94ccc5e5f5fb028aab805f9cd95379bd8b1b3
  patches:
    - disable-test-t6001.patch
    - disable-test-t1011.patch

build:
  number: 2
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make
    - cmake
    - pkgconfig
    - jq
  host:
    - python
    - flux-core
    - libhwloc
    - libboost-devel
    - libedit
    - yaml-cpp
    - pyyaml
    - jsonschema
    - lua-luaposix
    - cffi
    - ply
  run:
    - python
    - flux-core
    - libuuid
    - jansson
    - czmq

test:
  commands:
    - flux --help

about:
  home: https://flux-framework.org
  summary: Fluxion Graph-based Scheduler
  description: |
    Welcome to Fluxion, an advanced job scheduling software tool for 
    High Performance Computing (HPC). Fluxion combines graph-based 
    resource modeling with efficient temporal plan management schemes to 
    schedule a wide range of HPC resources (e.g., compute, storage, power 
    etc) in a highly scalable, customizable and effective fashion.
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://flux-framework.readthedocs.io/
  dev_url: https://github.com/flux-framework/flux-sched

extra:
  recipe-maintainers:
    - grondo
    - jan-janssen
