{% set name = "flux-sched" %}
{% set version = "0.48.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/flux-framework/flux-sched/releases/download/v{{ version }}/flux-sched-{{ version }}.tar.gz
  sha256: 8f8de89e445303e07b27912d4044862a8594d46b68d20dbb28b1e20bef198efe
  patches:
    - disable-t1025-rv1-reload.patch

build:
  number: 1
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make
    - cmake
    - pkgconfig
    - jq
    - ninja
  host:
    - python
    - flux-core
    - libhwloc
    - libboost-devel
    - libxml2-devel
    - libedit
    - yaml-cpp
    - pyyaml
    - jsonschema
    - lua-luaposix
    - cffi
    - ply
  run:
    - python
    - flux-core
    - libuuid
    - jansson
    - czmq

test:
  commands:
    - flux --help
    - flux start exit

about:
  home: https://flux-framework.org
  summary: Fluxion Graph-based Scheduler
  description: |
    Welcome to Fluxion, an advanced job scheduling software tool for 
    High Performance Computing (HPC). Fluxion combines graph-based 
    resource modeling with efficient temporal plan management schemes to 
    schedule a wide range of HPC resources (e.g., compute, storage, power 
    etc) in a highly scalable, customizable and effective fashion.
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://flux-framework.readthedocs.io/
  dev_url: https://github.com/flux-framework/flux-sched

extra:
  recipe-maintainers:
    - grondo
    - jan-janssen
